### ISSUE TITLE
Multiple devices using Particle-HAP

### ISSUE THREAD

**Issue by Dids** [ljezny/Particle-HAP#13]
Has anyone actually tried creating multiple devices using Particle-HAP, within the same HomeKit network/environment?

The readme briefly mentions changing the static key, but this doesn't seem to be enough, as I can't get additional accessories connected.

Right now I have separate sensor modules, which I'd like to deploy 4-5 of in the same environment/network, but I don't know if this is even possible with Particle-HAP, or if I should instead implement it so that one device is the master HomeKit device, while the others are simply communicating with over the network, creating new accessories when necessary?

**Comment by ljezny** [comment]
Hi, yes it's easily possible. This devices is called Bridge. Bridge is a set of independent HomeKit accessories. 
Look into my Homestation example. I am using it in my house. One photon acts like 3 windows shutters and 2 two relays. But keep in mind that more devices it describes more memory is used. So there's no hard limit, but you can try what works for you.

Also static accessory key is not a problem. Because it's just a "seed" for creating new keys. Every pairing creates new set of keys. But if you want, you can create a new accessory key, there's commented method generateAccesssoryKey, which generates a key. I just need to use a static key due to memory limitations of Photon.

I am closing it, since it is not an issue.

**Comment by Dids** [comment]
Thank you very much, both for this project and for providing the exact answer I was looking for!
