### ISSUE TITLE
Can't Add Accessory using iOS 13

### ISSUE THREAD

**Issue by sbehrends** [ljezny/Particle-HAP#7]
Hi everyone!

After flashing my photon with the `lightbulb` example, I am trying to pair it with Home App.
The PhotonLED is discoverable by the app, but when I tap it and enter the code I get a `Couldn't add PhotonLED; Home couldn't connect to this accessory`.

Hardware: Photon
Device OS: 1.3.0-rc.

Device:
iPhone X iOS 13.0 GM

Here are the events captured by Particle Console

```
event: homekit/accept
data: {"data":"192.168.0.20","ttl":60,"published_at":"2019-09-14T20:22:16.464Z","coreid":"310023001447343338333633"}

event: homekit/pair-setup
data: {"data":"192.168.0.20","ttl":60,"published_at":"2019-09-14T20:22:16.694Z","coreid":"310023001447343338333633"}

event: homekit/pair-setup
data: {"data":"192.168.0.20","ttl":60,"published_at":"2019-09-14T20:22:20.625Z","coreid":"310023001447343338333633"}

event: homekit/close
data: {"data":"192.168.0.20","ttl":60,"published_at":"2019-09-14T20:22:23.690Z","coreid":"310023001447343338333633"}

event: homekit/accept
data: {"data":"192.168.0.20","ttl":60,"published_at":"2019-09-14T20:22:26.419Z","coreid":"310023001447343338333633"}

event: homekit/pair-setup
data: {"data":"192.168.0.20","ttl":60,"published_at":"2019-09-14T20:22:26.612Z","coreid":"310023001447343338333633"}

event: homekit/pair-setup
data: {"data":"192.168.0.20","ttl":60,"published_at":"2019-09-14T20:22:30.639Z","coreid":"310023001447343338333633"}

event: homekit/pair-setup
data: {"data":"192.168.0.20","ttl":60,"published_at":"2019-09-14T20:22:33.741Z","coreid":"310023001447343338333633"}

event: homekit/close
data: {"data":"192.168.0.20","ttl":60,"published_at":"2019-09-14T20:22:37.677Z","coreid":"310023001447343338333633"}

event: homekit/accept
data: {"data":"192.168.0.20","ttl":60,"published_at":"2019-09-14T20:22:37.845Z","coreid":"310023001447343338333633"}

event: homekit/pair-setup
data: {"data":"192.168.0.20","ttl":60,"published_at":"2019-09-14T20:22:37.845Z","coreid":"310023001447343338333633"}
```

**Comment by ljezny** [comment]
Hi, i didn't tested with iOS13, since it's not officially released. But i will definetly fix it, bcs i am using several Photons in my house. Please be patient, i will look in to issue.

**Comment by ljezny** [comment]
Can you also test it with iOS 12 (i.e. on your ipad etc). To really confirm the iOS13 issue?

**Comment by sbehrends** [comment]
Just tried on an iPhone with 12.4.1 and having same issue.
I am on the same wifi network and so... let me know if there is any other troubleshooting I can do to help.

**Comment by ljezny** [comment]
Hi again,

i've updated library to latest version for lightbulb example. And test it and it worked. So i am unable to reproduce the issue. Please try the latest commit with updated library. Make sure you use proper pair code: 523-12-643 (otherwise crypto fails). Also, i've added "resetAll" Particle cloud function. You can call it with any parameter and Photon will forget all HomeKit settings, then just restart it. Also i would recommend to restart your iPhone (so HomeKit cache will be cleared).

If it still fails please provide iPhone log. Connect iPhone to your Mac, run Console app on Mac, switch to iPhone. Start pairing and export log and please send it to me. Don't worry, there are no secret values (passwords etc) shown in Log.

**Comment by sbehrends** [comment]
Hi ljezny,
got it to work pairing it from an iPad with iOS 10.3.3, and now I can control it from the other devices.
Still not sure what's wrong.

Any way... If I get more details I can reopen the issue with more details.

Great work!
